---
title: "About Alison"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Education
**University of Michigan, _Ann Arbor MI_**  
Graduated May 2019  
Bachelor of Science in Applied Mathematics  
GPA: 3.93 / 4.0

**Columbia University Mailman School of Public Health, _New York NY_**  
Expected Graduation 2021  
Master’s degree program in Biostatistics

# Work Experience
**Co-founder of BusyBox, LLC** May 2018 – May 2019

* Created and launched BusyBox LLC, an online subscription box startup that delivers safe sex supplies + fun and engaging educational materials related to sexual health & wellness, [getbusybox.com](www.getbusybox.com)
* Helped raise over $25,000 in seed funding, before leaving the company to pursue graduate education

**Researcher, _University of Michigan School of Public Health_** Summer 2018

* Conducted a paid, full-time research project through the Michigan undergraduate summer research program
* Created a mathematical model and performed simulations of HPV disease dynamics incorporating a game theory-based model of parents’ vaccine decision-making process

**Tutor, _University of Michigan Athletics Department_** Summer 2019

* Tutored student athletes in mathematics & statistics during the accelerated spring term


# Honors & Awards

* Phi Beta Kappa Honor Society Member
* University of Michigan James B. Angell Scholar

**Grand Prize Winner, “Innovation in Action” Competition** March 2018

* Social entrepreneurship competition through University of Michigan’s School of Public Health
* Won $10,000 grand prize for startup idea, BusyBox

**Zell Entrepreneurs 2018-19 Cohort Member, _Zell Lurie Institute_** September 2018 – May 2019

* Elite program of 12 student entrepreneurs working collaboratively to network & build relevant business skills
* Mentored by ZLI faculty at the University of Michigan Ross School of Business, and program sponsor Sam Zell


# Service & Leadership

**St. Mary’s Food Pantry Volunteer, _Harlem NY_** September 2019 – Present

* Volunteer at busy weekly food pantry to help serve our community with respect and compassion
* Greet guests assist them in picking out foods for a balanced diet while adhering to the shelter’s points policy

**Alpha Omicron Pi Sorority, VP of Chapter Development** January 2017 – January 2019

* Created chapter calendar, headed professional development and health & wellness committees,and managed use of designated funds for 80+ member sorority chapter

# Skills

* Proficient in R, Matlab, C++, Python, and Git/GitHub
* Highly experienced with Microsoft Office programs and Google suite
* Strong communication and interpersonal skills, both as a team member and leader
* 200-hour trained yoga instructor; CPR, AED, & First Aid certified